CREATE TABLE usuario
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE telefono
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero        BIGINT NOT NULL,
    codigo_ciudad BIGINT NOT NULL,
    codigo_pais   BIGINT NOT NULL,
    usuario_id    BIGINT NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);