-- secuencia para los id de usuario

CREATE SEQUENCE usuario_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE usuario
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre   VARCHAR(255) NOT NULL,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE telefono
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero        BIGINT NOT NULL,
    codigo_ciudad BIGINT NOT NULL,
    codigo_pais   BIGINT NOT NULL,
    usuario_id    BIGINT NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

-- Datos precargados...

INSERT INTO usuario (id, nombre, email, password)
VALUES (1, 'Fernando Torres', 'fernando_torres@nisum.com', '12345'),
       (2, 'Alan Brito', 'alan_brito@nisum.com', '123456'),
       (3, 'Esteban Dido', 'esteban_dido@nisum.com', '1234567');

INSERT INTO telefono (numero, codigo_ciudad, codigo_pais, usuario_id)
VALUES (98765432, 1, 56, 1),
       (98765433, 2, 56, 1),
       (98765423, 3, 57, 2),
       (98765434, 4, 58, 3);
